add gst_debug_set_threshold_from_string
go-gst/go-gst pull request #162
Opened 2024-12-27 12:16 UTC by beyeshooter

in my case i needed to catch all logs i used setLogFunction already provided, but it wont catch all logs from the beggings so i figured out that i must add it before alongside wioth SetLogFunction gst.Init(nil),  however it does exists in the library, that why i added DebugSetThresholdFromString, i hope it helps for anybody who's looking for the same function

2025-01-06 08:47 UTC, RSWilli requested changes
Thanks for the PR! I added some notes, let me know if you need help.

2025-01-06 08:47 UTC, RSWilli commented on gst/gst_debug.go
> +void cgoDebugSetThresholdFromStringFunction(const gchar* args)
This shouldn't be needed, you should be able to call `C.gst_debug_set_threshold_from_string(_args, reset)` directly from the go function below. These kinds of wrapper functions are only needed when you need to pass a function pointer to C.

2025-01-06 08:47 UTC, RSWilli commented on gst/gst_debug.go
> +func DebugSetThresholdFromString(args string) {
[`gst_debug_set_threshold_from_string`](https://gstreamer.freedesktop.org/documentation/gstreamer/gstinfo.html?gi-language=c#gst_debug_set_threshold_from_string) takes two arguments, please let users of `go-gst` decide whether or not to reset.

2025-01-06 09:09 UTC, beyeshooter commented on gst/gst_debug.go
> +void cgoDebugSetThresholdFromStringFunction(const gchar* args)
got it thank you !

2026-07-14 13:02 UTC, RSWilli commented
Now that the main branch uses generated bindings, this either is already implemented or needs to be redone.

2026-07-14 13:02 UTC, closed without merging