Register GstSample marshaling functions
go-gst/go-gst pull request #29
Opened 2023-08-28 18:03 UTC by biglittlebigben

Some of the gstreamer signals, such as the splitmuxsink format-location-full pass a GstSample in the signal callback. We need to register a GstSample marshaling function for this to work.

2023-08-28 20:30 UTC, RSWilli requested changes
I don't fully understand the use for this PR, but the [docs](https://gstreamer.freedesktop.org/documentation/gstreamer/gstsample.html?gi-language=c#gst_value_get_sample) say that it needs a `transfer:none`. I don't understand if this would be important here, though

2023-08-28 23:20 UTC, biglittlebigben commented
> I don't fully understand the use for this PR, but the [docs](https://gstreamer.freedesktop.org/documentation/gstreamer/gstsample.html?gi-language=c#gst_value_get_sample) say that it needs a `transfer:none`. I don't understand if this would be important here, though

I changed `wrapSample` to `FromGstSampleUnsafeNone`, which I believe should give proper ownership to the Go object. However, that's a change we may want to consider (in a separate PR) for other object marshaling (GstCaps for instance)?

2023-08-30 12:46 UTC, RSWilli commented
> > I don't fully understand the use for this PR, but the [docs](https://gstreamer.freedesktop.org/documentation/gstreamer/gstsample.html?gi-language=c#gst_value_get_sample) say that it needs a `transfer:none`. I don't understand if this would be important here, though
> 
> I changed `wrapSample` to `FromGstSampleUnsafeNone`, which I believe should give proper ownership to the Go object. However, that's a change we may want to consider (in a separate PR) for other object marshaling (GstCaps for instance)?

if you know of other such instances where that would be the case, please open issues. I think the bindings should strive to beeing as much "golang style" as possible, without any potential free errors

2023-08-30 12:47 UTC, RSWilli approved these changes

2023-08-30 12:47 UTC, merged